# Server settings
server:
  address: localhost
  #  servlet:
  #    context-path: /News
  tomcat:
    access_log_enabled: true
    max-connections: 800
  error:
    #    whitelabel:
    #      enabled: false
    path: /customError #default is /error
  session-timeout: 60

# SPRING PROFILES
spring:
  profiles:
    active: HangZhou
  application:
    name: CloudService
  datasource:
    master:
      name: master
      url: jdbc:mysql://127.0.0.1:3306/y3wegy?useUnicode=true&characterEncoding=utf-8
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
    business:
      name: business
      url: jdbc:mysql://127.0.0.1:3307/y3wegy?useUnicode=true&characterEncoding=utf-8
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      #    url: jdbc:mysql://192.168.99.100:3306/rui?useUnicode=true&characterEncoding=utf-8
      #    username: root
      #    password: root
      #    driver-class-name: com.mysql.cj.jdbc.Driver
      #使用druid数据源  https://github.com/alibaba/druid/wiki/DruidDataSource%E9%85%8D%E7%BD%AE%E5%B1%9E%E6%80%A7%E5%88%97%E8%A1%A8
  druid:
    filters: stat,wall,slf4j
    maxActive: 20
    initialSize: 3
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000 #test interval
    minEvictableIdleTimeMillis: 300000 #shortest life cycle
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 3000
    pool:
      jedis:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
    password: 12345
  #      sentinel:
  #        master: master1
  #        nodes: 192.168.99.100:32768
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    appname: CloudService
    metadata-map:
      Zone: HangZhou
  client:
    serviceUrl:
      HangZhou: http://y3wegy:12345@${eureka.instance.hostname}:9000/eureka/,http://y3wegy:12345@${eureka.instance.hostname}:9001/eureka/
      BengBu: http://y3wegy:12345@${eureka.instance.hostname}:9002/eureka/,http://y3wegy:12345@${eureka.instance.hostname}:9003/eureka/
    prefer-same-zone-eureka: true
    availability-zones:
      China: HangZhou,BengBu
    region: China
  # HTTP ENCODING
  http:
    encoding.charset: UTF-8
    encoding.enable: true
    encoding.force: true
  mvc:
    view:
      suffix: .html
## MyBatis
mybatis:
  typeAliasesPackage: com.y3wegy.**.bean.**
  configLocation: classpath:/mybatis-config.xml
  mapperLocations: classpath:/mapper/**/*.xml
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
---
# SPRING PROFILES
spring:
  profiles: HangZhou
server:
  port: 10100
management:
  server:
    port: 10200
service.customMsg: RUI1
---
# SPRING PROFILES
spring:
  profiles: HangZhou2
server:
  port: 10101
management:
  server:
    port: 10201
service.customMsg: RUI2