CREATE TABLE "MENU_INFO"
(	`ID` VARCHAR2(20) NOT NULL ,
   `MENU_CD` VARCHAR2(100) NOT NULL ,
   `DISPLAY_NAME` VARCHAR2(100) NOT NULL ,
   `MENU_LEVEL` NUMBER NOT NULL ,
   `MENU_ORDER` NUMBER NOT NULL ,
   `DISABLED` NUMBER(*,0) NOT NULL ,
   `MENU_TYPE` VARCHAR2(50)
)