CREATE TABLE `y3wegy`.`USER` (
  `ID` VARCHAR(20) NOT NULL,
  `USER_NAME` VARCHAR(45) NOT NULL,
  `NICK_NAME` VARCHAR(100) NULL,
  `PASSWORD` VARCHAR(400) NOT NULL,
  `USER_SEX` VARCHAR(5) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;
